### ISSUE TITLE
Your Script Broke

### ISSUE THREAD

**Issue by ghost** [TheGlockMisc/zippy-cli#1]
Hi,

Your script is broken, it won't download, ZippyShare changed the algorithm.

I use my own personal Bash implementation of a Zippyshare downloader, recently it broke, I hate when that happens. Thanks to the debug mode's Inspector of Firefox, I figured it out. I hope the solution of mine will help to bring back your script too.

Short: "+ a() + b() + c() + d + 5/5" is "+ 11" in reality.

```
<span id="omg" class="2" style="display:none;"></span>
<script type="text/javascript">
    var a = function() {return 1};
    var b = function() {return a() + 1};
    var c = function() {return b() + 1};
    var d = document.getElementById('omg').getAttribute('class');
    if (true) { d = d*2;}
    document.getElementById('dlbutton').href = "/d/XXXXXXX/"+(981255%1000 + a() + b() + c() + d + 5/5)+"/example.txt";
    if (document.getElementById('fimage')) {
        document.getElementById('fimage').href = "/i/XXXXXXX/"+(981255%1000 + a() + b() + c() + d + 5/5)+"/example.txt";
    }
</script>
```

The math is, simply:
981255%1000+11=266

I must notice, the style of putting raw stuff into "solve" without checking if this is really math does make me worry a little from the security perspective, but if I were to interfere, it all could be rewritten and become something else. I think everyone must be able to understand own code, and redoing my script in pure SH will be convoluted to say the least, so I won't do. Good Luck to you and your project!

**Comment by ghost** [comment]
And please, I notice you're involved in https://github.com/AvinashReddy3108/zippydl, maybe update it too, I guess.

**Comment by Rendevior** [comment]
Aight, working on it 😉

Edit: yeah, you're right. solving math when the scraping broke causing the whole script broke too because it is solving an integer.. This project is personal project too, i'm not well aware of errors lol. i used to upload/download vids here like 2 months ago and never use it again.

**Comment by Rendevior** [comment]
Thanks @skateron , that fixed the issue.
